import { StyleSheet } from "react-native";
import { COLOR } from "../../constant/Color";
import { WIDTH, HEIGHT, FONTSIZE } from "../../constant/Responsive";
import { FONTSTYLE } from "../../constant/Fonts";

const styleOther = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLOR.GRAYBLAND1,
    },
    viewheader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: WIDTH(3),
        width: WIDTH(100),
        height: HEIGHT(6),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
    },
    iconpromo: {
        width: WIDTH(5),
        height: HEIGHT(2.5),
        tintColor: COLOR.ORANGE,
    },
    textpromo: {
        fontSize: FONTSIZE(2.3),
        color: COLOR.BLACK,
        fontWeight: '700',
    },
    iconnotify: {
        width: WIDTH(3.9),
        height: HEIGHT(2.5),
    },
    textheader: {
        fontSize: FONTSIZE(2.8),
        fontFamily: FONTSTYLE.REGULAR,
        color: COLOR.BLACK,
        fontWeight: '700',
        left: WIDTH(3),
    },
    viewpromo: {
        width: WIDTH(12),
        height: WIDTH(7),
        borderRadius: WIDTH(5),
        backgroundColor: COLOR.WHITE,
        marginLeft: 'auto',
        elevation: 5,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: WIDTH(2),
    },
    viewnotify: {
        marginRight: WIDTH(4),
        width: WIDTH(10),
        height: WIDTH(7),
        borderRadius: WIDTH(5),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    body: {
        top: HEIGHT(2),
    },
    viewbody: {

    },
    viewutilities: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginHorizontal: WIDTH(3),
    },
    utilities: {
        width: WIDTH(45),
        height: HEIGHT(9),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
        borderRadius: WIDTH(3),
        justifyContent: 'center',
    },
    iconutilities: {
        left: WIDTH(4),
        width: WIDTH(5.3),
        height: HEIGHT(2.8),
        tintColor: COLOR.ORANGE,
    },
    iconrules: {
        left: WIDTH(4.5),
        width: WIDTH(6),
        height: HEIGHT(2.8),
        tintColor: COLOR.VIOLET,
    },
    textutilities: {
        fontSize: FONTSIZE(1.8),
        color: COLOR.BLACK,
        fontWeight: '700',
        left: WIDTH(4),
        top: HEIGHT(0.5),
    },
    music: {
        width: WIDTH(94),
        height: HEIGHT(9),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
        borderRadius: WIDTH(3),
        justifyContent: 'center',
        top: HEIGHT(2),
        marginHorizontal: WIDTH(3),
    },
    iconmusic: {
        left: WIDTH(3),
        width: WIDTH(8),
        height: HEIGHT(2.8),
        tintColor: COLOR.GREEN,
    },
    textother: {
        fontSize: FONTSIZE(2.3),
        fontFamily: FONTSTYLE.REGULAR,
        color: COLOR.BLACK,
        fontWeight: '700',
        left: WIDTH(4),
        top: HEIGHT(3.5),
        marginBottom: HEIGHT(1),
    },
    textbodysup: {
        fontSize: FONTSIZE(2.5),
        fontFamily: FONTSTYLE.REGULAR,
        color: COLOR.BLACK,
        fontWeight: '700',
        left: WIDTH(3.5),
        marginBottom: HEIGHT(1),
    },
    viewsupport: {
        width: WIDTH(94),
        height: HEIGHT(12.3),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
        borderRadius: WIDTH(3),
        justifyContent: 'center',
        top: HEIGHT(4),
        marginHorizontal: WIDTH(3),
        flexDirection: 'column',
        gap: HEIGHT(1.8),
    },
    support: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: WIDTH(3),
        left: WIDTH(3),
    },
    iconsupport: {
        width: WIDTH(4.3),
        height: HEIGHT(2.1),
        tintColor: COLOR.BLACK,
    },
    iconright: {
        width: WIDTH(3.5),
        height: HEIGHT(2.1),
        tintColor: COLOR.BLACK,
        marginLeft: 'auto',
        right: WIDTH(6),
    },
    textsupport: {
        fontSize: FONTSIZE(1.9),
        color: COLOR.BLACK,
        fontWeight: '500',
        letterSpacing: WIDTH(0.1),
    },
    line: {
        width: WIDTH(91),
        height: HEIGHT(0.05),
        backgroundColor: COLOR.GRAY,
        marginHorizontal: WIDTH(3),
    },
    textaccount: {
        fontSize: FONTSIZE(2.3),
        fontFamily: FONTSTYLE.REGULAR,
        color: COLOR.BLACK,
        fontWeight: '700',
        left: WIDTH(4),
        top: HEIGHT(6),
        marginBottom: HEIGHT(1),
    },
    viewaccount: {
        width: WIDTH(94),
        height: HEIGHT(27),
        backgroundColor: COLOR.WHITE,
        elevation: 5,
        borderRadius: WIDTH(3),
        justifyContent: 'center',
        top: HEIGHT(6),
        marginHorizontal: WIDTH(3),
        flexDirection: 'column',
        gap: HEIGHT(2),
    },
    account: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-around',
        left: WIDTH(3),
        gap: WIDTH(2),
    },
    iconaccount: {
        marginLeft: WIDTH(1.8),
    },
    iconaddress: {
        marginLeft: WIDTH(0.5),
    },
    iconsetting: {
        marginLeft: WIDTH(0.7),
    },
    iconlogout: {
        width: WIDTH(4.2),
        height: HEIGHT(2.2),
        tintColor: COLOR.BLACK,
        marginLeft: WIDTH(1.4),
    },
    textinfor: {
        fontSize: FONTSIZE(1.9),
        color: COLOR.BLACK,
        fontWeight: '500',
        letterSpacing: WIDTH(0.1),
        left: WIDTH(1.5),
    },
    textaddress: {
        fontSize: FONTSIZE(1.9),
        color: COLOR.BLACK,
        fontWeight: '500',
        letterSpacing: WIDTH(0.1),
        left: WIDTH(0.5),
    },
    textlogout: {
        fontSize: FONTSIZE(1.9),
        color: COLOR.BLACK,
        fontWeight: '500',
        letterSpacing: WIDTH(0.1),
        left: WIDTH(1.3),
    },
    lineinfor: {
        width: WIDTH(91),
        height: HEIGHT(0.08),
        backgroundColor: COLOR.GRAYBLAND,
        marginHorizontal: WIDTH(3),
    },
});


export default styleOther;